rhel7_job:
  tags:
    - rhel7
  variables:
    DOCS_BUILD_DIR: build/html
    DOCS_PUBLISH_ROOT: /dls/cs-www/reports/gitlab-ci/${CI_PROJECT_NAME}/docs
    DOCS_PUBLISH_URL: http://www.cs.diamond.ac.uk/reports/gitlab-ci/${CI_PROJECT_NAME}/docs
  coverage: '/TOTAL.*\s+(\d+\%)/'
  before_script:
    - pipenv install --dev
  script:
    - pipenv run tests
    - pipenv run docs
    - dls-python3 setup.py bdist_wheel
    - dls-py3 check --no-tag-check
  after_script:
    - pipenv run coverage html
    - mkdir -p ${DOCS_PUBLISH_ROOT}/latest
    - cp -rf ${DOCS_BUILD_DIR}/* ${DOCS_PUBLISH_ROOT}/latest

